name: Garage CI/CD

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: récuperer le depot gitbub
        uses: actions/checkout@v4
      - name: Installer les dépendances de node
        run: |
          cd code/server
          npm ci
      - name: Compiller typescript en JS
        run: |
          cd code/server
          rm -rf dist
          npm run compile
      - name: installer la base de données dans le serveur MySQL
        run: |
          sudo service mysql start
          cd code/server/mysql
          mysql -uroot -proot -e "SOURCE garage.test.sql;"
          mysql -uroot -proot -e "SHOW DATABASES;"
          mysql -uroot -proot -e "USE garage_test; TABLE garage_test.brand;"
      - name: exécuter les test
        run: |
          cd code/server
          npm run test
